import { name, State, GameMap } from '../type'
import { createComponent, generateEntity } from '@arekrado/canvas-engine'
import { createEntity } from '@arekrado/canvas-engine/entity/createEntity'
import { AIDifficulty } from '../systems/aiSystem'
import {
  gray,
  green,
  teal,
  orange,
  yellow,
  red,
  pink,
  purple,
} from '../utils/colors'

const maps: Omit<GameMap, 'name'>[] = [
  {
    entity: 'gameMap-1',
    players: [],
    grid: [
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
    ],
  },
  {
    entity: 'gameMap-2',
    players: [],
    grid: [
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
    ],
  },
  {
    entity: 'gameMap-3',
    players: [],
    grid: [
      [
        undefined,
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        undefined,
      ],
      [
        undefined,
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        undefined,
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        undefined,
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        undefined,
      ],
      [
        undefined,
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        undefined,
      ],
    ],
  },
  {
    entity: 'gameMap-4',
    players: [],
    grid: [
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
    ],
  },
  // {
  //   entity: 'gameMap-2',
  //   players: [
  //     {
  //       human: true,
  //       level: AIDifficulty.easy,
  //       color: teal,
  //     },
  //     {
  //       human: false,
  //       level: AIDifficulty.easy,
  //       color: green,
  //     },
  //     {
  //       human: false,
  //       level: AIDifficulty.easy,
  //       color: red,
  //     },
  //   ],
  //   grid: [
  //     [
  //       { player: 1, dots: 1 },
  //       { player: 2, dots: 2 },
  //       { player: 3, dots: 3 },
  //       { player: 3, dots: 3 },
  //       { player: 3, dots: 3 },
  //     ],
  //     [
  //       { player: 1, dots: 1 },
  //       { player: 2, dots: 2 },
  //       { player: 3, dots: 3 },
  //       { player: 3, dots: 3 },
  //       { player: 3, dots: 3 },
  //     ],
  //     [
  //       { player: 1, dots: 1 },
  //       { player: 2, dots: 2 },
  //       { player: 3, dots: 3 },
  //       { player: 3, dots: 3 },
  //       { player: 3, dots: 3 },
  //     ],
  //   ],
  // },
  // {
  //   entity: 'gameMap-3',
  //   players: [
  //     {
  //       human: true,
  //       level: AIDifficulty.easy,
  //       color: teal,
  //     },
  //     {
  //       human: false,
  //       level: AIDifficulty.easy,
  //       color: green,
  //     },
  //     {
  //       human: false,
  //       level: AIDifficulty.easy,
  //       color: red,
  //     },
  //   ],
  //   grid: [
  //     [
  //       { player: 1, dots: 1 },
  //       { player: 2, dots: 2 },
  //       { player: 3, dots: 3 },
  //       { player: 3, dots: 3 },
  //     ],
  //     [{ player: 1, dots: 1 }, undefined, undefined, { player: 3, dots: 3 }],
  //     [{ player: 1, dots: 1 }, undefined, undefined, { player: 3, dots: 3 }],
  //     [
  //       { player: 1, dots: 1 },
  //       { player: 2, dots: 2 },
  //       { player: 3, dots: 3 },
  //       { player: 3, dots: 3 },
  //     ],
  //   ],
  // },
  // {
  //   entity: 'gameMap-4',
  //   players: [
  //     {
  //       human: true,
  //       level: AIDifficulty.easy,
  //       color: teal,
  //     },
  //     {
  //       human: false,
  //       level: AIDifficulty.easy,
  //       color: green,
  //     },
  //     {
  //       human: false,
  //       level: AIDifficulty.easy,
  //       color: red,
  //     },
  //   ],
  //   grid: [
  //     [
  //       { player: 1, dots: 1 },
  //       { player: 2, dots: 2 },
  //       { player: 3, dots: 3 },
  //     ],
  //     [
  //       { player: 1, dots: 1 },
  //       { player: 2, dots: 2 },
  //       { player: 3, dots: 3 },
  //     ],
  //     [
  //       { player: 1, dots: 1 },
  //       { player: 2, dots: 2 },
  //       { player: 3, dots: 3 },
  //     ],
  //     [
  //       { player: 1, dots: 1 },
  //       { player: 2, dots: 2 },
  //       { player: 3, dots: 3 },
  //     ],
  //   ],
  // },
  // {
  //   entity: 'gameMap-5',
  //   players: [
  //     {
  //       human: true,
  //       level: AIDifficulty.easy,
  //       color: teal,
  //     },
  //     {
  //       human: false,
  //       level: AIDifficulty.easy,
  //       color: green,
  //     },
  //     {
  //       human: false,
  //       level: AIDifficulty.easy,
  //       color: red,
  //     },
  //   ],
  //   grid: [
  //     [
  //       { player: 1, dots: 1 },
  //       { player: 2, dots: 2 },
  //       { player: 3, dots: 3 },
  //     ],
  //     [
  //       { player: 1, dots: 1 },
  //       { player: 2, dots: 2 },
  //       { player: 3, dots: 3 },
  //     ],
  //     [
  //       { player: 1, dots: 1 },
  //       { player: 2, dots: 2 },
  //       { player: 3, dots: 3 },
  //     ],
  //   ],
  // },
]

export const gameMapsBlueprint = ({ state }: { state: State }): State => {
  maps.forEach((map) => {
    state = createEntity({ state, entity: map.entity })

    state = createComponent<GameMap, State>({
      state,
      data: {
        name: name.gameMap,
        ...map,
      },
    })
  })

  return state
}
