import { name, State, GameMap } from '../type'
import { createComponent } from '@arekrado/canvas-engine'
import { createEntity } from '@arekrado/canvas-engine/entity/createEntity'

const maps: Omit<GameMap, 'name'>[] = [
  {
    entity: 'gameMap-small-0',
    players: [],
    grid: [
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
    ],
  },
  {
    entity: 'gameMap-small-1',
    players: [],
    grid: [
      [
        undefined,
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        undefined,
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        undefined,
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        undefined,
      ],
    ],
  },
  {
    entity: 'gameMap-small-2',
    players: [],
    grid: [
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
    ],
  },
  {
    entity: 'gameMap-medium-0',
    players: [],
    grid: [
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
    ],
  },
  {
    entity: 'gameMap-medium-1',
    players: [],
    grid: [
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
    ],
  },
  {
    entity: 'gameMap-medium-2',
    players: [],
    grid: [
      [
        undefined,
        undefined,
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        undefined,
        undefined,
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        undefined,
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        undefined,
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        undefined,
        undefined,
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        undefined,
        undefined,
      ],
    ],
  },
  {
    entity: 'gameMap-0',
    players: [],
    grid: [
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
    ],
  },
  {
    entity: 'gameMap-1',
    players: [],
    grid: [
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
      ],
      [
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
    ],
  },
  {
    entity: 'gameMap-2',
    players: [],
    grid: [
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
    ],
  },
  {
    entity: 'gameMap-3',
    players: [],
    grid: [
      [
        undefined,
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        undefined,
      ],
      [
        undefined,
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        undefined,
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        undefined,
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        undefined,
      ],
      [
        undefined,
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        undefined,
      ],
    ],
  },
  {
    entity: 'gameMap-4',
    players: [],
    grid: [
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        undefined,
        undefined,
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
      [
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
        { player: -1, dots: 0 },
      ],
    ],
  },
]

export const gameMapsBlueprint = ({ state }: { state: State }): State => {
  maps.forEach((map) => {
    state = createEntity({ state, entity: map.entity })

    state = createComponent<GameMap, State>({
      state,
      data: {
        name: name.gameMap,
        ...map,
      },
    })
  })

  return state
}
