import { GameMap } from '../../type'
import {
  gray,
  green,
  orange,
  pink,
  purple,
  red,
  teal,
  yellow,
} from '../../utils/colors'
import { AIDifficulty } from '../../systems/aiSystem'

export const campaign43: Omit<GameMap, 'name'> = {
  entity: 'gameMap-campaign-43',
  campaignNumber: 43,
  locked: false,
  players: [
    {
      human: true,
      color: teal,
      level: AIDifficulty.easy,
    },
    {
      human: false,
      color: red,
      level: AIDifficulty.medium,
    },
    // {
    //   human: false,
    //   color: green,
    //   level: AIDifficulty.medium,
    // },
    // {
    //   human: false,
    //   color: yellow,
    //   level: AIDifficulty.medium,
    // },
    // {
    //   human: false,
    //   color: orange,
    //   level: AIDifficulty.hard,
    // },
    // {
    //   human: false,
    //   color: pink,
    //   level: AIDifficulty.hard,
    // },
    // {
    //   human: false,
    //   color: gray,
    //   level: AIDifficulty.hard,
    // },
    // {
    //   human: false,
    //   color: purple,
    //   level: AIDifficulty.hard,
    // },
  ],
  grid: [
    [
      { player: 0, dots: 1 },
      { player: 0, dots: 1 },
      { player: 0, dots: 0 },
      { player: 0, dots: 0 },
      { player: 0, dots: 0 },
      { player: 0, dots: 0 },
      { player: 1, dots: 1 },
      { player: 0, dots: 1 },
    ],
    [
      { player: 0, dots: 1 },
      { player: 0, dots: 1 },
      { player: 0, dots: 0 },
      { player: 0, dots: 0 },
      { player: 0, dots: 0 },
      { player: 0, dots: 0 },
      { player: 0, dots: 1 },
      { player: 0, dots: 1 },
    ],
    [
      { player: 0, dots: 0 },
      { player: 0, dots: 0 },
      undefined,
      { player: 0, dots: 0 },
      { player: 0, dots: 0 },
      undefined,
      { player: 0, dots: 0 },
      { player: 0, dots: 0 },
    ],
    [
      { player: 0, dots: 0 },
      { player: 0, dots: 0 },
      { player: 0, dots: 0 },
      { player: 0, dots: 1 },
      { player: 0, dots: 2 },
      { player: 0, dots: 0 },
      { player: 0, dots: 0 },
      { player: 0, dots: 0 },
    ],
    [
      { player: 0, dots: 0 },
      { player: 0, dots: 0 },
      { player: 0, dots: 0 },
      { player: 0, dots: 2 },
      { player: 0, dots: 1 },
      { player: 0, dots: 0 },
      { player: 0, dots: 0 },
      { player: 0, dots: 0 },
    ],
    [
      { player: 0, dots: 0 },
      { player: 0, dots: 0 },
      undefined,
      { player: 0, dots: 0 },
      { player: 0, dots: 0 },
      undefined,
      { player: 0, dots: 0 },
      { player: 0, dots: 0 },
    ],
    [
      { player: 0, dots: 1 },
      { player: 0, dots: 1 },
      { player: 0, dots: 0 },
      { player: 0, dots: 0 },
      { player: 0, dots: 0 },
      { player: 0, dots: 0 },
      { player: 0, dots: 1 },
      { player: 0, dots: 1 },
    ],
    [
      { player: 0, dots: 1 },
      { player: 0, dots: 1 },
      { player: 0, dots: 0 },
      { player: 0, dots: 0 },
      { player: 0, dots: 0 },
      { player: 0, dots: 0 },
      { player: 0, dots: 1 },
      { player: 0, dots: 1 },
    ],
  ],
}
