import { GameMap } from '../../type'
import {
  gray,
  green,
  orange,
  pink,
  red,
  teal,
  yellow,
} from '../../utils/colors'
import { AIDifficulty } from '../../systems/aiSystem'

export const campaign38: Omit<GameMap, 'name'> = {
  entity: 'gameMap-campaign-38',
  campaignNumber: 38,
  locked: true,
  players: [
    {
      human: true,
      color: teal,
      level: AIDifficulty.easy,
    },
    {
      human: false,
      color: red,
      level: AIDifficulty.easy,
    },
    {
      human: false,
      color: green,
      level: AIDifficulty.easy,
    },
    {
      human: false,
      color: yellow,
      level: AIDifficulty.medium,
    },
    {
      human: false,
      color: orange,
      level: AIDifficulty.medium,
    },
    {
      human: false,
      color: pink,
      level: AIDifficulty.medium,
    },
    {
      human: false,
      color: gray,
      level: AIDifficulty.hard,
    },
  ],
  grid: [
    [
      undefined,
      undefined,
      { player: 3, dots: 1 },
      { player: 3, dots: 1 },
      { player: 3, dots: 1 },
      { player: 3, dots: 1 },
      undefined,
      undefined,
    ],
    [
      undefined,
      undefined,
      { player: 4, dots: 1 },
      { player: 4, dots: 1 },
      { player: 4, dots: 1 },
      { player: 4, dots: 1 },
      undefined,
      undefined,
    ],
    [
      { player: 1, dots: 1 },
      { player: 0, dots: 1 },
      { player: -1, dots: 0 },
      { player: -1, dots: 0 },
      { player: -1, dots: 0 },
      { player: -1, dots: 0 },
      { player: 5, dots: 1 },
      { player: 6, dots: 1 },
    ],
    [
      { player: 1, dots: 1 },
      { player: 0, dots: 1 },
      { player: -1, dots: 0 },
      { player: -1, dots: 0 },
      { player: -1, dots: 0 },
      { player: -1, dots: 0 },
      { player: 5, dots: 1 },
      { player: 6, dots: 1 },
    ],
    [
      { player: 1, dots: 1 },
      { player: 0, dots: 1 },
      { player: -1, dots: 0 },
      { player: -1, dots: 0 },
      { player: -1, dots: 0 },
      { player: -1, dots: 0 },
      { player: 5, dots: 1 },
      { player: 6, dots: 1 },
    ],
    [
      { player: 1, dots: 1 },
      { player: 0, dots: 1 },
      { player: -1, dots: 0 },
      { player: -1, dots: 0 },
      { player: -1, dots: 0 },
      { player: -1, dots: 0 },
      { player: 5, dots: 1 },
      { player: 6, dots: 1 },
    ],
    [
      undefined,
      undefined,
      { player: 2, dots: 1 },
      { player: 2, dots: 1 },
      { player: 2, dots: 1 },
      { player: 2, dots: 1 },
      undefined,
      undefined,
    ],
    [
      undefined,
      undefined,
      { player: 0, dots: 1 },
      { player: 0, dots: 1 },
      { player: 0, dots: 1 },
      { player: 0, dots: 1 },
      undefined,
      undefined,
    ],
  ],
}
