import { GameMap } from '../../type'
import { green, orange, pink, red, teal, yellow } from '../../utils/colors'
import { AIDifficulty } from '../../systems/aiSystem'

export const campaign34: Omit<GameMap, 'name'> = {
  entity: 'gameMap-campaign-34',
  campaignNumber: 34,
  locked: true,
  players: [
    {
      human: true,
      color: teal,
      level: AIDifficulty.easy,
    },
    {
      human: false,
      color: red,
      level: AIDifficulty.easy,
    },
    {
      human: false,
      color: green,
      level: AIDifficulty.easy,
    },
    {
      human: false,
      color: yellow,
      level: AIDifficulty.medium,
    },
    {
      human: false,
      color: orange,
      level: AIDifficulty.medium,
    },
    {
      human: false,
      color: pink,
      level: AIDifficulty.medium,
    },
  ],
  grid: [
    [
      { player: 0, dots: 1 },
      { player: 0, dots: 1 },
      { player: 2, dots: 1 },
      { player: 2, dots: 1 },
      { player: 1, dots: 1 },
      { player: 1, dots: 1 },
      { player: 3, dots: 1 },
      { player: 3, dots: 1 },
    ],
    [
      { player: 0, dots: 1 },
      { player: 0, dots: 1 },
      { player: 2, dots: 1 },
      { player: 2, dots: 1 },
      { player: 1, dots: 1 },
      { player: 1, dots: 1 },
      { player: 3, dots: 1 },
      { player: 3, dots: 1 },
    ],
    [
      { player: 4, dots: 1 },
      { player: 4, dots: 1 },
      { player: 5, dots: 1 },
      { player: 5, dots: 1 },
      { player: 0, dots: 1 },
      { player: 0, dots: 1 },
      { player: 2, dots: 1 },
      { player: 2, dots: 1 },
    ],
    [
      { player: 4, dots: 1 },
      { player: 4, dots: 1 },
      { player: 5, dots: 1 },
      { player: 5, dots: 1 },
      { player: 0, dots: 1 },
      { player: 0, dots: 1 },
      { player: 2, dots: 1 },
      { player: 2, dots: 1 },
    ],
    [
      { player: 1, dots: 1 },
      { player: 1, dots: 1 },
      { player: 3, dots: 1 },
      { player: 3, dots: 1 },
      { player: 4, dots: 1 },
      { player: 4, dots: 1 },
      { player: 5, dots: 1 },
      { player: 5, dots: 1 },
    ],
    [
      { player: 1, dots: 1 },
      { player: 1, dots: 1 },
      { player: 3, dots: 1 },
      { player: 3, dots: 1 },
      { player: 4, dots: 1 },
      { player: 4, dots: 1 },
      { player: 5, dots: 1 },
      { player: 5, dots: 1 },
    ],
    [
      { player: 0, dots: 1 },
      { player: 0, dots: 1 },
      { player: 2, dots: 1 },
      { player: 2, dots: 1 },
      { player: 5, dots: 1 },
      { player: 5, dots: 1 },
      { player: 1, dots: 1 },
      { player: 1, dots: 1 },
    ],
    [
      { player: 0, dots: 1 },
      { player: 0, dots: 1 },
      { player: 2, dots: 1 },
      { player: 2, dots: 1 },
      { player: 5, dots: 1 },
      { player: 5, dots: 1 },
      { player: 1, dots: 1 },
      { player: 1, dots: 1 },
    ],
  ],
}
